### ISSUE TITLE
`send_timeout` alternative

### ISSUE THREAD

**Issue by indietyp** [asynchronics/tachyonix#5]
I am currently looking for a replacement for the `tokio` `mpsc` channel, which has increased throughput and the ability to cancel channels from a `Sender`, and it seems like `tachyonix` is ticking all the boxes!

The only thing I am currently uncertain about is the cancel safety of `.send()` in the sense that I want to emulate [`send_timeout()`](https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.Sender.html#method.send_timeout) because there's no dedicated method of doing so I thought of using `tokio::time::timeout(duration, sender.send())`, but I am unsure if this is supported and won't lead to any side effects. So any help in clarifying this would be appreciated!

Thank you so much in advance.

**Comment by sbarral** [comment]
Yes, this should work. Internally, this relies on the `async_event::WaitUntil` primitive, which [supports cancellation](https://github.com/asynchronics/async-event/blob/b1596a3efee20809372f170e783fc9b76c6f63e7/src/lib.rs#L221-L241).

There is also a [test](https://github.com/asynchronics/tachyonix/blob/e274e9f1be9888022cbe1d4cd1a2e5e0dbf83e5a/tests/general.rs#L200-L236) for sender cancellation.

**Comment by indietyp** [comment]
The only thing that might be complicate this solution tho is that once the duration has elapsed and the timeout was triggered, the item that was supposed to be sent has been lost.

tokio solves this over a permit like API, where you first acquire a permit, and then once acquired send the item. This allows you timeout the permit process and not lose the item. (This is also helpful in other scenarios, for example, where you first need to make sure you have space for an item before you actually create it or do any meaningful work)

**Comment by sbarral** [comment]
I see, you are right, there is currently no way to get the value back when the future is cancelled.

I don't remember the details of the permit system in tokio's channel: does it ensure that the timeout is relative to when channel capacity is booked (i.e. when the value is actually queued), or is it relative to when the value is dequeued/received? By the way I am not sure what you mean by "make sure you have space for an item": can't you use `try_send` for this purpose?

In any case, senders in Tachyonix retain ownership of the value until it is sent, so *in theory* one could implement a `send_timeout` method where the deadline is relative to the moment when the value is queued, but even so there are 2 practical issues:

1) introducing a timer would put a hard dependency on tokio, which goes against the intentional minimalism of Tachyonix (even with feature-gating),
2) the generated future would need to be implemented by hand, which is always a bit tricky (all this complexity is now elegantly hidden in `async_event::WaitUntil`).

A solution that avoids issue 1) above would be to introduce a method such as:

```rust
pub async fn send_timeout(&self, value: T, timeout: impl Future<Output=()>) -> Result<(), SendTimoutError<T>>
```

where the last argument could be a `tokio::time::Sleep` future. 

I would accept a PR for this if you were willing to make one.

**Comment by sbarral** [comment]
I had a deeper look at this. While I am pretty sure it can work, I haven't found a way to implement it without a lot of work so I'm afraid this will need to wait for a smarter or more courageous soul...

**Comment by indietyp** [comment]
Thank you. I'll try to give it a try, though I am not sure I'll be able to succeed. Writing that sort of performant correct async code is quite tricky to get right.

**Comment by indietyp** [comment]
The `permit` API cannot fully be modeled with `try_send`, because with permit, you can do:

```rs
let sender = ...;

let permit = sender.permit().await?;

// I have a safe spot in the queue
// if I `drop` that spot will be reclaimed

let x = something_that_involves_significant_work();

permit.send(x);
```

`try_send` doesn't solve this because before sending, I need to have my item ready.

Hope that makes sense!

**Comment by sbarral** [comment]
There is some good news: after thinking a bit more about it I realized that this could in fact be done pretty painlessly. It was easier to add support for this directly in the `async-event` crate so this is what I did (a new version was published a couple of minutes ago).
I will publish a new version of Tachyonix soon which contains not only a `send_timeout` but also a `recv_timeout`.

Edit: Tachyonix 0.3.0 was published with timeout support so I'm closing this issue, but please don't hesitate to provide feedback in this thread and re-open the issue if some concerns still need to be addressed.
